apiVersion: v1
kind: Namespace
metadata:
  name:  monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: monitoring
data:
  config.yaml: |-
    logLevel: warn
    logFormat: json
    maxEventAgeSeconds: 599
    metricsNamePrefix: event_exporter_
    route:
      routes:
        - match:
            # get notifications about system pods
            - namespace: "kube-system"
            - kind: "Pod|Deployment|ReplicaSet|DaemonSet|StatefulSet"
              reason: "Killing|BackOff|FailedKillPod|FailedCreatePodContainer|Failed|NetworkNotReady|InspectFailed"
              receiver: "slack"
        - match:
            # nodes
            - kind: "Node"
            - reason: "Rebooted|Shutdown|NodeNotReady|NodeReady|NodeNotSchedulable"
              receiver: "slack"
        - match:
            # other
            - kind: "Pod|Deployment|ReplicaSet|DaemonSet|StatefulSet"
            - reason: "BackOff|Killing|NetworkNotReady"
              receiver: "slack"
    receivers:
      - name: "dump"
        stdout: {}
      - name: "slack"
        slack:
          token: "SLACK_TOKEN"
          channel: "SLACK_CHANNEL_NAME"
          message: "{{ .Message }}"
          fields:
            namespace: "{{ .Namespace }}"
            reason: "{{ .Reason }}"
            object: "{{ .Namespace }}"
