# internal taskfile

version: '3'

tasks:
  chmod:
    cmds:
      - chmod 777 ./output
      - chmod 777 ./output/*.yml
  ssh-keys:

    cmds:
      - rm -rf ./output/id_ed25519*
      - ssh-keygen -t ed25519 -f ./output/id_ed25519 -N "" -C "landlubber"
      - task: chmod

  inventory:
    cmds:
      - cp ./playbooks/default-inventory.yml ./output/inventory.yml
      - echo 'review ./output/inventory.yml file'
      - echo 'write your hcloud token in it'
      - task: chmod

  run:
    cmds:
      - echo 'landlubber running'
      - task: ssh-keys
      - task: ansible-provision-network
      - task: ansible-key_to_hcloud
      - task: ansible-provision-vms
      - task: ansible-selinux
      - task: ansible-dns
      - task: ansible-initial-packages
      - task: ansible-initial-services
      - task: ansible-helm

  ansible-provision-network:
    cmds:
      - ansible-playbook -i ./output/inventory.yml ./playbooks/provision_network.yaml

  ansible-key_to_hcloud:
    cmds:
      - ansible-playbook -i ./output/inventory.yml ./playbooks/key_to_hcloud.yaml

  ansible-provision-vms:
    cmds:
      - ansible-playbook -i ./output/inventory.yml ./playbooks/provision_vms.yaml

  ansible-selinux:
    cmds:
      - ansible-playbook -i ./output/inventory.yml ./playbooks/selinux.yaml

  ansible-dns:
    cmds:
      - ansible-playbook -i ./output/inventory.yml ./playbooks/dns.yaml

  ansible-initial-packages:
    cmds:
      - ansible-playbook -i ./output/inventory.yml ./playbooks/initial_packages.yaml

  ansible-initial-services:
    cmds:
      - ansible-playbook -i ./output/inventory.yml ./playbooks/initial_services.yaml

  ansible-helm:
    cmds:
      - ansible-playbook -i ./output/inventory.yml ./playbooks/helm.yaml
