---
- name: Install packages
  hosts: all
  gather_facts: true
  tasks:
    - name: Start and enable iscsid
      ansible.builtin.service:
        name: iscsid
        state: started
        enabled: true
    - name: Stop and disable rpcbind
      ansible.builtin.service:
        name: rpcbind
        state: stopped
        enabled: false
