---
- name: Provision VMs on Hetzner Cloud
  hosts: node1
  gather_facts: false
  tasks:
    - name: Install python3-hcloud on ansible host
      delegate_to: localhost
      ansible.builtin.apt:
        name: python3-hcloud
    - name: Provision VM \#1 on hcloud
      delegate_to: localhost
      register: output_1
      hetzner.hcloud.server:
        api_token: "{{ hcloud_token }}"
        name: "{{ node_name_1 }}"
        server_type: cax11
        image: rocky-9
        location: "{{ hcloud_region_1 }}"
        ssh_keys:
          - landlubber-key
        private_networks:
          - "{{ hcloud_network }}"
    - name: Provision VM \#2 on hcloud
      delegate_to: localhost
      register: output_2
      hetzner.hcloud.server:
        api_token: "{{ hcloud_token }}"
        name: "{{ node_name_2 }}"
        server_type: cax11
        image: rocky-9
        location: "{{ hcloud_region_2 }}"
        ssh_keys:
          - landlubber-key
        private_networks:
          - "{{ hcloud_network }}"
    - name: Provision VM \#3 on hcloud
      delegate_to: localhost
      register: output_3
      hetzner.hcloud.server:
        api_token: "{{ hcloud_token }}"
        name: "{{ node_name_3 }}"
        server_type: cax11
        image: rocky-9
        location: "{{ hcloud_region_3 }}"
        ssh_keys:
          - landlubber-key
        private_networks:
          - "{{ hcloud_network }}"
    - name: Update inventory.yml with IP of VM \#1
      delegate_to: localhost
      ansible.builtin.replace:
        path: ../output/inventory.yml
        regexp: "NODEIP1"
        replace: "'{{ output_1.hcloud_server.ipv4_address }}'"
        backup: false
    - name: Update inventory.yml with IP of VM \#2
      delegate_to: localhost
      ansible.builtin.replace:
        path: ../output/inventory.yml
        regexp: "NODEIP2"
        replace: "'{{ output_2.hcloud_server.ipv4_address }}'"
        backup: false
    - name: Update inventory.yml with IP of VM \#3
      delegate_to: localhost
      ansible.builtin.replace:
        path: ../output/inventory.yml
        regexp: "NODEIP3"
        replace: "'{{ output_3.hcloud_server.ipv4_address }}'"
        backup: false
