---
- name: Disable SELinux globally
  hosts: all
  gather_facts: true
  tasks:
    - name: Install python3-libselinux
      ansible.builtin.dnf:
        name: python3-libselinux
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled
