nodes:
  hosts:
    node1:
      ansible_host: ansible-node
      ansible_port: 22
      ansible_user: root
      ansible_password: 123
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  vars:
    node_name_1: kube-node-1
    node_name_2: kube-node-2
    node_name_3: kube-node-3
    # /etc/hosts is tricky in docker containers
    etc_hosts: /etc/hosts2

    # additional applications to deploy to cluster
    install_longhorn: true
    install_victoria_metrics: true
    install_k8s_dashboard: true
    install_event_exporter: true
    install_kubetail: true

    # event exporter config
    slack_token: WRITE_SLACK_TOKEN_HERE
    slack_channel_name: "k8s"
