name: test-playbooks

on:
    workflow_run:
        workflows:
            - Docker
        branches:
            - main
        types:
            - completed

jobs:
    test-playbooks:
        name: test-playbooks
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: /landlubber
        container: ghcr.io/pgulb/landlubber:main
        services:
            ansible-node:
                image: ghcr.io/pgulb/rocky-ansible-tester:master
                volumes:
                    - /sys/fs/cgroup:/sys/fs/cgroup:rw
                options: --privileged --cgroupns=host
                # ports:
                #     - 2222:22
        steps:
            - name: install sshpass and ping
              run: apt-get update; apt-get install sshpass iputils-ping -y
            - name: ping the node
              run: ping -4 -c 1 ansible-node
            - name: test disabling selinux
              run: ansible-playbook -i ./playbooks/test-inventory.yaml ./playbooks/selinux.yaml
            - name: test adding dns settings
              run: ansible-playbook -i ./playbooks/test-inventory.yaml ./playbooks/dns.yaml
            - name: test installing initial packages
              run: ansible-playbook -i ./playbooks/test-inventory.yaml ./playbooks/initial_packages.yaml
            - name: test setting up initial services
              run: ansible-playbook -i ./playbooks/test-inventory.yaml ./playbooks/initial_services.yaml
            - name: test installing helm
              run: ansible-playbook -i ./playbooks/test-inventory.yaml ./playbooks/helm.yaml
