name: test-playbooks

on:
    workflow_run:
        workflows:
            - Docker
        branches:
            - main
        types:
            - completed

jobs:
    test-playbooks:
        name: test-playbooks
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: /landlubber
        container: ghcr.io/pgulb/landlubber:main
        services:
            ansible-node:
                image: ghcr.io/pgulb/rocky-ansible-tester:master
                volumes:
                    - /sys/fs/cgroup:/sys/fs/cgroup:rw
                options: --privileged --cgroupns=host
                ports:
                    - 2222:22
        steps:
            - name: install sshpass
              run: apt-get update; apt-get install sshpass -y
            - name: test disabling selinux
              run: ansible-playbook -i ./playbooks/test-inventory.yaml ./playbooks/selinux.yaml
